### ISSUE TITLE
I need help with my code

### ISSUE THREAD

**Issue by doc-han** [VarunManchanda/Google-KickStart-2020#1]
Below is my code for Allocation and it isn't being accepted. Can you help me find out why? because I'm unable to see what's wrong.
```cpp
#include <bits/stdc++.h>
using namespace std;

int main(){
    ios_base::sync_with_stdio(0); 
    cin.tie(0);
    int t;
    cin>>t;
    for(int i=1;i<=t;i++){
        int n,b;
        cin>>n>>b;
        int arr[n];
        for(int j=0;j<n;j++) cin>>arr[j];
        sort(arr, arr+n); 
        int k = 0;
        while(b - arr[k] >= 0){
            b -= arr[k++];
        }
        cout << "Case #" << i << ": " << k << endl;
    }
    return 0;
}
```

**Comment by doc-han** [comment]
@VarunManchanda

**Comment by VarunManchanda** [comment]
Sure

**Comment by doc-han** [comment]
@VarunManchanda found anything? my code wasn't accepted but yours was accepted. I'm quite confused.

Your code adds up values to a variable s to check whether it exceeds b while mine subtract from b and checks whether it gets lower that 0.
